name: Validate Resource Types

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Radius version number to use (e.g. 0.51.0, edge). Leave empty for default.'
        required: false
        default: ''
        type: string

jobs:
  validate-resource-types:
    runs-on: ubuntu-latest
    name: Validate Resource Types and Recipes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 16
      - name: Set up k3d
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Set up ORAS
        uses: oras-project/setup-oras@v1
        with:
          version: '1.2.0'
      - name: Install Radius CLI
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            make install-radius-cli RAD_VERSION="${{ inputs.version }}"
          else
            make install-radius-cli
          fi
      - name: Create Radius Cluster
        run: make create-radius-cluster
      - name: Build
        run: make build
